Repository SOPT-32-CDS/BaeMin-AOS, pull requests merged in 2023-05, with the labels that each got.

#11 Store Detail 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/haeti/baeminaos/data/local/StoreDetailDataClass.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/storedetail/StoreDetailActivity.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/storedetail/adapter/ChoiceRVAdapter.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/storedetail/adapter/OptionRVAdapter.kt
  app/src/main/res/drawable/background_count.xml
  app/src/main/res/drawable/checkbox_selector.xml
  app/src/main/res/drawable/ic_best_menu.png
  app/src/main/res/drawable/ic_check_outline.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_store_detail_example.png
  app/src/main/res/layout/activity_store_detail.xml
  app/src/main/res/layout/item_store_choice.xml
  app/src/main/res/layout/item_store_option.xml
  app/src/main/res/layout/toolbar.xml
  app/src/main/res/values/strings.xml
Labels: jihyeon 🐣

#16 장바구니 뷰 서버통신 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/haeti/baeminaos/data/remote/CartCountRequestDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/CartCountResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/CartDeleteResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/CartItemResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/CartOrderResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/service/CartService.kt
  app/src/main/java/sopt/haeti/baeminaos/module/CartApiFactory.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartActivity.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartCountViewModel.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartDeleteViewModel.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartItemViewModel.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartOrderViewModel.kt
  app/src/main/res/layout/activity_cart.xml
Labels: sangho 🍀

#15 주문하기 메인 뷰 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/haeti/baeminaos/data/local/StoreMenu.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/DummyDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/StoreDetailResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/store/StoreActivity.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/store/StoreExpandableAdapter.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/store/StoreMenuInnerAdapter.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/store/ToggleAnimation.kt
  app/src/main/java/sopt/haeti/baeminaos/util/ItemDiffCallback.kt
  app/src/main/res/drawable-xhdpi/ic_together_3.png
  app/src/main/res/drawable/bg_sesco.xml
  app/src/main/res/drawable/ic_arrow.png
  app/src/main/res/drawable/ic_best_menu.png
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/ic_heart_3.png
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_three_person.png
  app/src/main/res/drawable/img_menu.png
  app/src/main/res/drawable/img_store.png
  app/src/main/res/drawable/img_store_info.png
  app/src/main/res/layout/activity_store.xml
  app/src/main/res/layout/item_store_menu.xml
  app/src/main/res/layout/item_store_menu_detail.xml
Labels: taehee 🐺

#22 메인 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/haeti/baeminaos/data/local/StoreList.kt
  app/src/main/java/sopt/haeti/baeminaos/data/remote/StoreListResponseDto.kt
  app/src/main/java/sopt/haeti/baeminaos/data/service/HomeStoreListService.kt
  app/src/main/java/sopt/haeti/baeminaos/module/StoreApiFactory.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/home/HomeActivity.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/home/HomeStoreAdapter.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/home/HomeViewModel.kt
  app/src/main/res/drawable/bg_white_border.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_chip_basic.png
  app/src/main/res/drawable/ic_chip_coupon.png
  app/src/main/res/drawable/ic_down_arrow.png
  app/src/main/res/drawable/ic_filled_star.png
  app/src/main/res/drawable/ic_for_one_person.png
  app/src/main/res/drawable/img_store_list.png
  app/src/main/res/drawable/nav.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_store_list.xml
  app/src/main/res/values/themes.xml
Labels: taehee 🐺

#24 장바구니 서버통신 진짜 구현
  app/src/main/java/sopt/haeti/baeminaos/data/service/CartService.kt
  app/src/main/java/sopt/haeti/baeminaos/presentation/cart/CartActivity.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_store.xml
Labels: sangho 🍀
